-- ============================================================
-- Bible Book Intros (English)
-- Source: bibleread.online (Recovery Version)
-- Generated: 2026-05-13
-- ============================================================
-- Run this file first, then the outline files.

DELETE FROM bible_book_intros WHERE lang = 'en';

INSERT INTO bible_book_intros (book_abbr, lang, author, time_of_writing, place_of_writing, time_period_covered, subject) VALUES
-- ── OLD TESTAMENT ────────────────────────────────────────────
('Gen',  'en', 'Moses, the author of the five books of the Law',
 'Probably about 1490 B.C., when Exodus was written',
 'In the wilderness east of Egypt',
 'From the beginning of creation (1:1) until approximately 1653 B.C., the death of Joseph (50:26)',
 ''),

('Exo',  'en', 'Moses',
 'Approximately 1490 B.C., in the second year after the exodus, after the tabernacle was erected',
 'In the wilderness and at Mount Sinai',
 'From approximately 1706 B.C., when Jacob came to Egypt (1:1), until one year after the exodus from Egypt (40:17) in 1490 B.C.',
 ''),

('Lev',  'en', 'Moses',
 'Approximately 1490 B.C.',
 'In the wilderness, near Mt. Sinai',
 'One month, from the tabernacle''s erection on the first day of the first month in the second year after the exodus through the first day of the second month, 1490 B.C.',
 ''),

('Num',  'en', 'Moses',
 'Approximately 1452 B.C., before the end of Israel''s forty-year wilderness wandering',
 'In the plains of Moab by the Jordan River at Jericho (Num. 36:13)',
 'Almost thirty-nine years, 1490—1452 B.C.',
 ''),

('Deut', 'en', 'Moses; the final chapter (34) was likely written by someone else',
 'Approximately 1452 B.C.',
 'In the plains of Moab',
 'The last two months of 1452 B.C., the fortieth year after the exodus from Egypt',
 ''),

('Josh', 'en', 'Joshua (24:26)',
 '1452—1426 B.C.',
 'The plains of Moab and Shechem in Canaan',
 'Approximately twenty-seven years, 1452—1426 B.C.',
 ''),

('Judg', 'en', 'Probably Samuel',
 'The eleventh century B.C.',
 'Canaan',
 'About 305 years, from about 1425 B.C. to 1120 B.C., from after Joshua''s death to the death of Samson',
 ''),

('Ruth', 'en', 'Probably Samuel',
 'The eleventh century B.C., after the rule of the judges and in the time of the kings',
 'Moab and Bethlehem in Judah',
 'About eleven years, from about 1322 B.C. to about 1312 B.C.',
 ''),

('1Sam', 'en', 'Samuel wrote 1 Sam. 1—24; Nathan the prophet and Gad the seer wrote the remainder of 1 Samuel and all of 2 Samuel',
 'The eleventh century B.C.',
 'Ephraim and Judah',
 'About 155 years, approximately 1171—1017 B.C.',
 ''),

('2Sam', 'en', 'Samuel wrote 1 Sam. 1—24; Nathan the prophet and Gad the seer wrote the remainder of 1 Samuel and all of 2 Samuel',
 'The eleventh century B.C.',
 'Ephraim and Judah',
 'Approximately 155 years, 1171—1017 B.C.',
 ''),

('1Kgs', 'en', 'Unknown; some have supposed Jeremiah wrote them',
 'Some time during the Babylonian captivity, after 561 B.C.',
 'Probably in Jerusalem',
 '1 Kings covers 119 years (1015—897 B.C.), from the death of David to the reign of Ahaziah',
 ''),

('2Kgs', 'en', 'Unknown; some have supposed Jeremiah wrote them',
 'Some time during the Babylonian captivity, after 561 B.C.',
 'Probably in Jerusalem',
 '336 years, from 896 B.C. to 561 B.C., from the reign of Jehoram to Evil-merodach in Babylon',
 ''),

('1Chr', 'en', 'Probably Ezra',
 'Probably after 458 B.C., during the reign of Artaxerxes the king of Persia',
 'Perhaps in Jerusalem',
 'About forty-one years (excluding genealogy in chs. 1—9), from 1056 B.C. to 1015 B.C., from Saul''s death to David''s death',
 ''),

('2Chr', 'en', 'Probably Ezra',
 'Probably after 458 B.C.',
 'Perhaps in Jerusalem',
 'About 476 years, from 1015 B.C. to 539 B.C., from Solomon''s reign to the proclamation of Cyrus',
 ''),

('Ezra', 'en', 'Ezra, a descendant of Aaron and a priest and scribe skilled in the law of Moses',
 'After 457 B.C.',
 'Jerusalem',
 'Approximately eighty-two years, 539 B.C. to 457 B.C.',
 ''),

('Neh',  'en', 'Nehemiah, who was cupbearer to Artaxerxes the king of Persia and Babylon',
 'After 433 B.C.',
 'Jerusalem',
 'Approximately twelve years, from 445 B.C. to 433 B.C.',
 ''),

('Esth', 'en', 'Probably Mordecai (9:20, 23), Esther''s cousin',
 'Around 474 B.C., in the twelfth month of the twelfth year of Ahasuerus',
 'Susa, capital of the Persian Empire',
 'At least ten years, from 484 B.C. to 474 B.C.',
 ''),

('Job',  'en', 'Job',
 'Approximately 2000 B.C.',
 'The land of Uz',
 'Approximately 200 years around 2000 B.C.; Job lived another 140 years after his trials',
 ''),

('Ps',   'en', 'David (73 psalms), sons of Korah (12), Asaph (12), Solomon (2), Ethan (1), Moses (1), and 49 unknown authors',
 'Beginning in the eleventh century B.C. (except Psa. 90, written by Moses in the fifteenth century B.C.)',
 'Mainly Jerusalem',
 '',
 ''),

('Prov', 'en', 'Main writers: Solomon (chs. 1—24), compiled by Hezekiah''s men (chs. 25—29), Agur (ch. 30), King Lemuel (ch. 31)',
 'Approximately 1000 B.C. for Solomon''s sections; around 700 B.C. for Hezekiah''s additions',
 'Probably Jerusalem',
 '',
 ''),

('Eccl', 'en', 'Solomon (1:1, 12; cf. 1 Kings 4:32)',
 'About 977 B.C., after Solomon''s fall (1 Kings 11:1-8)',
 'Jerusalem',
 '',
 ''),

('Song', 'en', 'Solomon (1:1)',
 'Around 1000 B.C.',
 'Jerusalem',
 '',
 'The spiritual journey of pursuing Christ for satisfaction, deliverance from self, living in resurrection and ascension, and preparation for rapture'),

('Isa',  'en', 'Isaiah (1:1)',
 'The eighth century B.C.',
 'Jerusalem',
 'About sixty-four years, from around 760 B.C. to about 696 B.C.',
 ''),

('Jer',  'en', 'Jeremiah (1:1)',
 'Late seventh and early sixth centuries B.C.',
 'Jerusalem and Egypt',
 'At least forty-two years, from 628 B.C. (thirteenth year of Josiah''s reign) through sometime after 586 B.C.',
 ''),

('Lam',  'en', 'Jeremiah (according to the Septuagint; cf. 2 Chron. 35:25)',
 'Shortly after the destruction of Jerusalem in 586 B.C.',
 'Jerusalem',
 '',
 ''),

('Ezek', 'en', 'Ezekiel (1:3)',
 'The sixth century B.C.',
 'By the river Chebar, in the village of Tel-abib, near Babylon',
 'Twenty-two years, from 593 B.C. (fifth year of Jehoiachin''s captivity) to 571 B.C. (29:17)',
 ''),

('Dan',  'en', 'Daniel',
 'The sixth century B.C.',
 'Babylon',
 'A period of sixty-eight years, from 605 B.C. to 537 B.C.',
 ''),

('Hos',  'en', 'Hosea (1:1)',
 'Approximately a 60-year period, from circa 785 B.C. to approximately 725 B.C.',
 'The northern kingdom of Israel',
 '',
 ''),

('Joel', 'en', 'Joel (1:1)',
 'About 800 B.C., probably after the prophet Elisha',
 'The southern kingdom of Judah',
 '',
 ''),

('Amos', 'en', 'Amos (1:1)',
 'Approximately 787 B.C.',
 'Bethel, in the northern kingdom of Israel',
 '',
 ''),

('Obad', 'en', 'Obadiah',
 'About 880 or 587 B.C.',
 'The southern kingdom of Judah',
 '',
 ''),

('Jonah','en', 'Jonah (1:1)',
 'About 862 B.C., at the time of the prophet Elisha',
 'Nineveh, the capital of Assyria',
 '',
 ''),

('Mic',  'en', 'Micah (1:1)',
 'About 750-710 B.C., at the time of Isaiah and Hosea',
 'The southern kingdom of Judah',
 '',
 ''),

('Nah',  'en', 'Nahum (1:1)',
 'Approximately 713 B.C., the year in which Sennacherib invaded Judah',
 'The southern kingdom of Judah',
 '',
 ''),

('Hab',  'en', 'Habakkuk (1:1)',
 'About 626 B.C., close to the time of the Babylonian invasion',
 'The southern kingdom of Judah',
 '',
 ''),

('Zeph', 'en', 'Zephaniah (1:1)',
 'About 630 B.C., at the time of Habakkuk and Jeremiah',
 'Judah',
 '',
 ''),

('Hag',  'en', 'Haggai (1:1)',
 'Approximately 520 B.C., during the second year of Darius Hystaspes',
 'Jerusalem',
 '',
 ''),

('Zech', 'en', 'Zechariah (1:1)',
 'Approximately 520—518 B.C.',
 'Jerusalem',
 '',
 ''),

('Mal',  'en', 'Malachi (1:1)',
 'About 430 B.C., at Nehemiah''s time',
 'Jerusalem',
 '',
 ''),

-- ── NEW TESTAMENT ────────────────────────────────────────────
('Mt',   'en', 'Matthew (also called Levi), formerly a tax collector, later an apostle (9:9)',
 'Approximately A.D. 37—40, shortly after the Lord''s resurrection',
 'Probably the land of Judea',
 '',
 ''),

('Mk',   'en', 'Mark',
 'Between A.D. 67 and 70, after the death of the apostle Paul',
 'Possibly Rome',
 '',
 ''),

('Lk',   'en', 'Luke',
 'Approximately A.D. 60, before Acts was written',
 'Probably Caesarea, when Paul was imprisoned there',
 '',
 ''),

('Jn',   'en', 'The apostle John, son of Zebedee (21:20, 24)',
 'Approximately A.D. 90',
 'Perhaps Ephesus',
 '',
 ''),

('Acts', 'en', 'Luke',
 'A.D. 67 or 68, after the Gospel of Luke was written',
 'Perhaps Rome',
 '',
 ''),

('Rm',   'en', 'The apostle Paul (1:1)',
 'Approximately A.D. 60, during Paul''s third ministry journey',
 'Corinth',
 '',
 ''),

('1Co',  'en', 'The apostle Paul',
 'Approximately A.D. 59, during the end of Paul''s three-year residence in Ephesus',
 'Ephesus',
 '',
 ''),

('2Co',  'en', 'The apostle Paul (1:1)',
 'Approximately A.D. 60, before the Epistle to the Romans',
 'Macedonia',
 '',
 ''),

('Gal',  'en', 'The apostle Paul (1:1)',
 'Approximately A.D. 54, during Paul''s second ministry journey',
 'Corinth',
 '',
 ''),

('Eph',  'en', 'The apostle Paul (1:1)',
 'Approximately A.D. 64',
 'Rome, where Paul was imprisoned (3:1; 4:1; 6:20)',
 '',
 ''),

('Phil', 'en', 'Paul with Timothy, slaves of Christ Jesus',
 'Approximately A.D. 64',
 'Rome, during Paul''s imprisonment',
 '',
 ''),

('Col',  'en', 'Paul the apostle with Timothy the brother (1:1)',
 'Approximately A.D. 64',
 'Rome, during Paul''s imprisonment',
 '',
 ''),

('1Th',  'en', 'Paul with Silvanus and Timothy (1:1)',
 'Approximately A.D. 54, during Paul''s second ministry journey while in Corinth',
 'Corinth',
 '',
 ''),

('2Th',  'en', 'Paul with Silvanus and Timothy',
 'Approximately A.D. 54',
 'Corinth',
 '',
 ''),

('1Ti',  'en', 'The apostle Paul (1:1)',
 'Approximately A.D. 65, after Paul''s first Roman imprisonment',
 'Probably Macedonia',
 '',
 ''),

('2Ti',  'en', 'The apostle Paul (1:1)',
 'Approximately A.D. 67, during Paul''s second imprisonment, near the time of his martyrdom',
 'A Roman prison',
 '',
 ''),

('Tit',  'en', 'The apostle Paul (1:1)',
 'Approximately A.D. 65, after Paul''s first Roman imprisonment',
 'Nicopolis',
 '',
 ''),

('Phm',  'en', 'Paul the apostle with Timothy the brother',
 'Approximately A.D. 64, shortly before Paul was released from his first Roman imprisonment',
 'A Roman prison',
 '',
 ''),

('Heb',  'en', 'Apparently the apostle Paul, who alone was qualified to write the deep, high, and rich content',
 'Perhaps A.D. 67, after Paul''s release from his first Roman imprisonment',
 'Perhaps Miletus',
 '',
 ''),

('Jas',  'en', 'James, a slave of God and of the Lord Jesus Christ; the Lord''s flesh brother',
 'Perhaps around A.D. 50, prior to the decline of the church',
 'Probably Jerusalem',
 '',
 ''),

('1Pe',  'en', 'Peter, an apostle of Jesus Christ (1:1)',
 'Approximately A.D. 64',
 'Babylon on the Euphrates',
 '',
 ''),

('2Pe',  'en', 'Peter, a slave and apostle of Jesus Christ',
 'Approximately A.D. 69, following Paul''s martyrdom',
 'Possibly Rome',
 '',
 ''),

('1Jn',  'en', 'The apostle John, author of the Gospel of John',
 'Approximately A.D. 90—95, after John''s return from exile on Patmos',
 'Ephesus',
 '',
 ''),

('2Jn',  'en', 'John the elder',
 'After the first Epistle of John was written',
 'Ephesus',
 '',
 ''),

('3Jn',  'en', 'John the elder',
 'After the second Epistle of John was written',
 'Ephesus',
 '',
 ''),

('Jude', 'en', 'Jude, a slave of Jesus Christ and a flesh brother of James and of the Lord',
 'Approximately A.D. 69, before Jerusalem''s destruction',
 'Jerusalem or Judea',
 '',
 ''),

('Rev',  'en', 'The apostle John (1:1, 9)',
 'Approximately A.D. 90, while John was in exile on the island of Patmos',
 'The island of Patmos (1:9)',
 '',
 '');
