-- ============================================================
-- English Book Subjects (scraped from bibleread.online)
-- Generated: 2026-05-15
-- ============================================================

UPDATE bible_book_intros SET subject = 'God Created, Satan Corrupted, Man Fell, and Jehovah Promised to Save' WHERE book_abbr = 'Gen' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Christ is the Redemption, Salvation, and Supply of God''s People and the Means for Them to Worship and Serve God So That in Him They May Be Built Up with God Together for Them and God to Meet, Communicate, and Dwell Mutually' WHERE book_abbr = 'Exo' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Christ is Everything in the Fellowship, Service, and Life of God''s Redeemed' WHERE book_abbr = 'Lev' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Christ is the Meaning of Life, the Testimony, the Center of God''s People, and the Leader, the Way, and the Goal of Their Journey and Fighting' WHERE book_abbr = 'Num' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Christ is the Instructor and Leader of the People of God That They May Be Able to Enter into the Heavenly Territory and Participate in His Riches' WHERE book_abbr = 'Deut' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Israel''s Occupying and Possessing the Good Land for the Carrying Out of God''s Economy' WHERE book_abbr = 'Josh' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Israel''s Forsaking God, Suffering Defeat by Their Enemies, and Becoming Rotten' WHERE book_abbr = 'Judg' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'A Complete Prefigure of the Gentile Sinners'' Being Brought, with Israel, God''s Elect, into the Divine Inheritance through the Redemption of Christ in Their Union with Him' WHERE book_abbr = 'Ruth' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Illustrations of the Way to Enjoy the God-given Good Land' WHERE book_abbr = '1Sam' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Illustrations of the Way to Enjoy the God-given Good Land' WHERE book_abbr = '2Sam' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'God''s Governmental Dealing in God''s Economy with the Devastation and Ruin of the Divine Kingship on Earth by the Kings and the Tragic Issue of the Just Dealing of God' WHERE book_abbr = '1Kgs' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'God''s Governmental Dealing in God''s Economy with the Devastation and Ruin of the Divine Kingship on Earth by the Kings and the Tragic Issue of the Just Dealing of God' WHERE book_abbr = '2Kgs' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'A Full Chronology of God''s Move in Man''s History from Adam through Samuel to Israel''s Return from Their Captivity, with a Presentation of Some of the Important Details of God''s Dealing with the Kings of Judah' WHERE book_abbr = '1Chr' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'A Full Chronology of God''s Move in Man''s History from Adam through Samuel to Israel''s Return from Their Captivity, with a Presentation of Some of the Important Details of God''s Dealing with the Kings of Judah' WHERE book_abbr = '2Chr' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Return of the Children of Israel from Their Captivity and the Rebuilding of the House of God as the Initiation of God''s Recovery among His Elect for His Testimony on the Earth according to His Economy' WHERE book_abbr = 'Ezra' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Rebuilding of the Wall of the City of Jerusalem as a Continual Recovery among God''s Elect for His Testimony for the Accomplishment of His Economy' WHERE book_abbr = 'Neh' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Very God Who Chose Israel as His Elect Becoming a Hidden God to Them to Take Care of Them Secretly and to Save Them Openly While Acting in Secrecy during Their Captivity among the Gentile Nations' WHERE book_abbr = 'Esth' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Purpose of God''s Dealing with His Holy One' WHERE book_abbr = 'Job' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Expressions of the Sentiments, Feelings, Impressions, and Experiences of Godly Men Seeking and Contacting God through Their Praises, Prayers, and Singing with Exultation' WHERE book_abbr = 'Ps' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Words of Wisdom Teaching People How to Behave and How to Build Up Their Character in the Human Life' WHERE book_abbr = 'Prov' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Teachings of Solomon, Showing That the Human Life in the Corrupted World Is a Vanity, a Chasing after the Wind' WHERE book_abbr = 'Eccl' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The History of Love in an Excellent Marriage, Revealing the Progressive Experience of an Individual Believer''s Loving Fellowship with Christ' WHERE book_abbr = 'Song' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Salvation of Jehovah through the Incarnated, Crucified, Resurrected, Ascended, and Coming Christ' WHERE book_abbr = 'Isa' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Christ Being Made the Righteousness of Jehovah to God''s Elect as Their Center and Circumference, in God''s Dealings with Israel and the Nations' WHERE book_abbr = 'Jer' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Expression of Jeremiah''s Sorrow and Love over the Holy City and the Holy People of God' WHERE book_abbr = 'Lam' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'God''s Appearing to Man in Glory, His Judgment upon Both His People and the Nations, and His Recovery of His Chosen People for the Building Up of a Dwelling Place as a Mutual Abode and Complete Expression for and of Himself' WHERE book_abbr = 'Ezek' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Destiny of Israel Apportioned Out by God — The Contents of the Seventy Weeks' WHERE book_abbr = 'Dan' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Jehovah as Salvation to the Adulterous and Apostate Israel in Receiving Her Back and Restoring Her' WHERE book_abbr = 'Hos' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Devastation of the Human Government on Israel in Four Stages and Christ''s Destruction of the Devastators and His Reign among Israel in the Restoration' WHERE book_abbr = 'Joel' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Jehovah''s Judgments on Israel and the Surrounding Nations, with the Issue of Restoration' WHERE book_abbr = 'Amos' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Jehovah''s Dealing with Esau, and Jacob''s Victory for the Kingdom of Jehovah' WHERE book_abbr = 'Obad' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Jehovah''s Salvation Reaching Even unto the Gentile City Nineveh' WHERE book_abbr = 'Jonah' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Jehovah''s Reproof on Israel and His Restoration of Israel' WHERE book_abbr = 'Mic' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Jehovah''s Judgment on Nineveh as the Capital of the Evil Assyria' WHERE book_abbr = 'Nah' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Righteous Judgment of God First on Israel by the Chaldeans and Then on the Chldeans by the Nations' WHERE book_abbr = 'Hab' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Jehovah''s Judgment on Israel and on the Nations and His Salvation to the Gentiles and to Israel' WHERE book_abbr = 'Zeph' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Jehovah''s Dealing with the Returned Captives for the Building of His House' WHERE book_abbr = 'Hag' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Jehovah''s Hearty Consolation and Promise to His Chastised Chosen People through the Redemption of Christ, Who in His Humiliation Became Their Suffering Companion in Their Captivity' WHERE book_abbr = 'Zech' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Jehovah''s Dealing with the Sons of Levi (the Priests among Israel) and with the Sons of Jacob (the People of Israel)' WHERE book_abbr = 'Mal' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Gospel of the Kingdom — Proving That Jesus Christ Is the King-Savior' WHERE book_abbr = 'Mt' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Gospel of God — Proving That Jesus Christ Is the Slave-Savior' WHERE book_abbr = 'Mk' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Gospel of the Forgiveness of Sins — Proving That Jesus Christ Is the Man-Savior' WHERE book_abbr = 'Lk' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Gospel of Life — Proving That Jesus Christ Is God the Savior Coming as Life to Propagate Himself' WHERE book_abbr = 'Jn' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Propagation of the Resurrected Christ in His Ascension, by the Spirit, through the Disciples, for the Producing of the Churches—The Kingdom of God' WHERE book_abbr = 'Acts' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Gospel of God — To Make Sinners Sons of God to Constitute the Body of Christ, Which Is Expressed as the Local Churches' WHERE book_abbr = 'Rom' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Christ and His Cross as the Solution to All Problems in the Church' WHERE book_abbr = '1Co' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The New Covenant Ministry and Its Ministers' WHERE book_abbr = '2Co' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Christ Replacing the Law and Being versus Religion and Tradition' WHERE book_abbr = 'Gal' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Church — The Mystery of Christ, the Body of Christ as the Fullness of Christ, Becoming the Fullness of God' WHERE book_abbr = 'Eph' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Experiencing Christ — Taking Christ as Our Living, Pattern, Goal, Power, and Secret' WHERE book_abbr = 'Phil' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Christ — The All-inclusive One, Having the First Place in All Things as the Mystery and Embodiment of God, as the Head and Constituent of the Church, as the Allotted Portion, Life, Constituent, and Hope of the Saints, and as the Body of All Positive Things' WHERE book_abbr = 'Col' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'A Holy Life for the Church Life — Serving the Living God, Conducting Ourselves in a Holy Manner, and Waiting for the Lord''s Coming' WHERE book_abbr = '1Thes' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Encouragement and Correction concerning the Holy Life for the Church Life' WHERE book_abbr = '2Thes' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'God''s Economy concerning the Church' WHERE book_abbr = '1Tim' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Inoculation against the Decline of the Church' WHERE book_abbr = '2Tim' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Maintenance of Order in the Church' WHERE book_abbr = 'Titus' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'An Illustration of the Believers'' Equal Status in the New Man' WHERE book_abbr = 'Phm' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Christ Being Superior to Judaism and Everything Related to It, and the New Covenant Which He Consummated Being Better than the Old Covenant' WHERE book_abbr = 'Heb' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Practical Christian Perfection' WHERE book_abbr = 'Jas' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Christian Life under the Government of God' WHERE book_abbr = '1Pet' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Divine Provision and the Divine Government' WHERE book_abbr = '2Pet' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'The Fellowship of the Divine Life' WHERE book_abbr = '1Jn' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Prohibition against Participation in Heresy' WHERE book_abbr = '2Jn' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Encouragement to the Fellow Workers in the Truth' WHERE book_abbr = '3Jn' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Contending for the Faith' WHERE book_abbr = 'Jude' AND lang = 'en';
UPDATE bible_book_intros SET subject = 'Christ as the Center of God''s Administration according to God''s Eternal Economy' WHERE book_abbr = 'Rev' AND lang = 'en';
